### ISSUE TITLE
Why not use this one?

### ISSUE THREAD

**Issue by skinkie** [openTdataCH/ojp-adapter#2]
https://github.com/bliksemlabs/ojp-java-model

**Comment by phirzel** [comment]
I thought I use it, where do you mean?

**Comment by skinkie** [comment]
What is the added value of the repository is the question :-)

**Comment by phirzel** [comment]
Ahh, understood. I have no idea about your further goals, where you want to go with "ojp-java-model" ? CEN-EU license is copyleft, right? As a swiss I am not ready for that yet ;-)

If you are really open to join we might talk about ideas ..

**Comment by skinkie** [comment]
The license was copied from netex-java-model. But I am trying to understand what the aim of this repo is.

**Comment by phirzel** [comment]
..improved the readme today..

1) hope to find contibutors to enhance and test this adapter (still lots of todos), to improve SBB customer information based on OJP in a future scenario
2) SKI+ is using it for tests already as a plugin within SBB official Journey-Service
3) Could become a complete adapter for other transport-organisations based on OJP one day
4) easy usage for hackatons related to public transport
